---

- hosts: localhost
  connection: local
  tasks:
  - add_host:
      name: "{{ hostname }}"
      group: target
    no_log: true

- hosts: target
  become: yes
  vars:
    via_proxy_name: nrproxy #The name the proxy presents

  tasks:
     
# Install tinyproxy & Setup config file from Template
    - name: Install Tinyproxy 
      yum:
        name: tinyproxy
        state: latest
        
    - name: Set up the New Relic config file from template
      template:
        src: "./{{ environment }}-tinyproxy.conf.j2"
        dest: "/etc/tinyproxy/tinyproxy.conf"
        owner: "tinyproxy"
        group: "tinyproxy"
        mode: "0775"
      tags:
        - reverse-proxy

# Start Tiny Proxy
    - name: Start Tinyproxy
      service:
        name: tinyproxy
        state: started